### ISSUE TITLE
AUTH_LOGIN_CHECK issue on Dokuwiki 2017-02-19e "Frusterick Manners"

### ISSUE THREAD

**Issue by Ryonez** [bagley/dokuwiki-securelogin#5]
Installed this plugin, however the securelogin admin page shows this notice:

> Your version of dokuwiki not generate AUTH_LOGIN_CHECK event, plugin not work!

**Comment by bagley** [comment]
What version of Dokuwiki are you using? ( it shows it the Admin page http://example.net/start?do=admin )

Is this showing on the "Secure login configuration" page? ( http://example.net/start?do=admin&page=securelogin )

Is this when the page loads? Have you generated a new key pair under "Generate new key pair"?

**Comment by Ryonez** [comment]
The version is in the title of the issue, and yes, that the securelogin page mentioned.

Telling it to generate a new keypair does nothing, no changes on the page. Testing it reports the test was sent on plan text.

**Comment by bagley** [comment]
That error message happens when Dokuwiki's authentication won't allow the plugin to integrate with it. 2017-02-19e allows that, so I can't see why it's happening. And with that test failing, that's why your tests show it going through as plain text. So it sounds like there's something up with your setup. I installed a new site, installed the plugin, it created the keys, and the test went through encrypted (as did the logins). As it is, I'm not able to reproduce this error.

Did you do the usual dokuwiki install?
Do you have any other plugins enabled?
Do you have a different authentication plugin enabled besides the plain one?
What's your setup? Linux, windows, included webserver, Apache, NGINX? Have you tried it on another host?
What version of php are you using? In a module, or php-fpm? Shared hosting?
Do the key and ini files exist in your website files? (I assume they do, just checking):
  data/cache/securelogin.key
  data/cache/securelogin.ini

I need this info and any other info to try to be able to reproduce the error. Otherwise it's almost impossible to know what's causing this.

**Comment by Ryonez** [comment]
Sorry for the delay, I've been preoccupied.

Did you do the usual dokuwiki install?
I'm using the `mprasil/dokuwiki` docker container.

Do you have any other plugins enabled?
Actually a few, though a few are disable as well: 
https://i.imgur.com/12jjbnv.png
https://i.imgur.com/yq3qSAY.png

Do you have a different authentication plugin enabled besides the plain one?
I'm currently using "oauth"

What's your setup? Linux, windows, included webserver, Apache, NGINX? Have you tried it on another host?
The docker is being run on an unRAID server (Slackware based). The docker webserver is lighttpd, and is being run through a letsencrypt reverse proxy container.No I have not tried it on another host, the effort wouldn't be worth it when I need it to run in this environment.

What version of php are you using? In a module, or php-fpm? Shared hosting?
Docker seems to have this `PHP Version => 7.0.28-0ubuntu0.16.04.1`

Do the key and ini files exist in your website files? (I assume they do, just checking):
data/cache/securelogin.key
data/cache/securelogin.ini
Both files exist.

Hopefully this will help.

**Comment by bagley** [comment]
Thanks for sending all of that. It did help me to make the environment. However, I was not able to reproduce the issue. I did setup the docker environment, installed that docker container, installed the plugin, and then tested to see if I could reproduce it, and it loaded the Admin > Secure login configuration page without issue. 

I generated the keys, removed and regenerated them, logged in and out, and still I did not see the issue nor any other issue.

I then went through and installed all of the plugins that were on the list in the image you send, tested, but I was still not able to find the issue. I thought it may have been in with one of the two factor authentication plugins, but they worked like a charm.

I'm sorry for taking so long to get back to you. I do appreciate you reporting this. If you are still having issues, try disabling the other plugins one by one until it works. If you find one that it is not working with, please let me know so I can take a closer look.

If you are still not able to get this to work, then the issue would be much deeper. It may even be that s a core file of Dokuwiki is corrupt or missing.
