### ISSUE TITLE
CAPTCHA Plugin Issue

### ISSUE THREAD

**Issue by ajreaper** [bagley/dokuwiki-securelogin#7]
Hiya. I just installed this plugin to add some extra security to my DW installation (Greebo) and noticed it doesn't appear to play nice with the CAPTCHA Plugin (https://www.dokuwiki.org/plugin:captcha). Basically, when it is enabled, it causes CAPTCHA to be able to be ignored (wrong entry, right entry, no entry). When the field is empty or incorrect, it just give your the regular error message after you've been logged in.

"Sorry, but the CAPTCHA wasn't answered correctly. Maybe you're not human at all?"

On last thing: is there supposed to be a checkbox for "secure login" on the login page? I managed to hide it using CSS, but wanted to ask if that was normal. It seems to be checked by default.

Thanks!

**Comment by bagley** [comment]
It appears both of the plugins are managing the login at the same time. From glancing over it, Securelogin will need to check that the Captcha is entered right: https://www.dokuwiki.org/plugin:captcha#helper_methods

However, I am not going to fix this. I am planning on Archiving this plugin, unless someone wants to adopt it. And I just don't have the time to incorporate a feature like this. You are welcome to submit a patch/PR to fix this if you would like.

I'll update the page that it causes the Captcha plugin not to work properly.

As you are already hiding the checkbox, I would say to not use this plugin in your current setup. Otherwise the user doesn't know if the password is being encrypted.

**Comment by ajreaper** [comment]
Okay. Thanks for the heads up. Maybe if I have some time I'll take a crack at it, but I'm mostly just a front end developer type person.

Just as an FYI, I didn't want to give the user an option to NOT encrypt the password, which is why I was hiding it.
